# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: PowerShell@2
  displayName: 'Clean NAT'
  inputs:
    targetType: filePath
    filePath: 'windows-network-conainer-cleanup.ps1'
    arguments: '-Cleanup -ForceDeleteAllSwitches'    
- task: DockerCompose@0
  inputs:
    dockerComposeCommand: up
    dockerComposeFile: '.\build-docker-compose.yml'
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK 2.1.300'
  inputs:
    version: 2.1.300

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: .\build.ps1
    arguments: -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true